name: EnhancedHomes
description: A modern and feature-rich homes plugin.
authors: [Noma, rvHoney]
website: https://enhancedplugins.com
version: '1.2.1'
api-version: '1.17'
main: com.enhancedplugins.enhancedhomes.EnhancedHomes
permissions:
  enhancedhomes.homes:
    description: Allows players to list all their homes
    default: true
  enhancedhomes.homes.other:
    description: Allows players to list all their homes
    default: op
  enhancedhomes.home:
    description: Allows players to teleport to their homes
    default: true
  enhancedhomes.home.other:
    description: Allows players to teleport to other players' homes
    default: op
  enhancedhomes.crossworldtp.bypass:
    description: Allows players to teleport between worlds
    default: op
  enhancedhomes.warmup.bypass:
    description: Allows players to bypass the teleportation warmup
    default: op
  enhancedhomes.sethome:
    description: Allows players to set a home
    default: true
  enhancedhomes.sethome.max.<number>:
    description: Allows players to set a home at the specified number
    default: op
  enhancedhomes.sethome.unlimited:
    description: Allows players to set an unlimited number of homes
    default: op
  enhancedhomes.delhome:
    description: Allows player to delete one of his home.
    default: true
  enhancedhomes.delhome.other:
    description : Allows players to delete an other player's home.
    default : op
  enhancedhomes.enhancedhomesreload:
    description: Allows players to reload the plugin
    default: op
commands:
  homes:
    description: List all your homes
    usage: /homes [player]
    permission: enhancedhomes.homes
  home:
      description: Teleport to your home
      usage: /home <name>
      permission: enhancedhomes.home
  sethome:
    description: Set a home
    usage: /sethome <name>
    permission: enhancedhomes.sethome
  delhome:
    description : Delete a home
    usage: /delhome [name]
    permission: enhancedhomes.delhome
    permission-message: You do not have permission to use this command.
  enhancedhomesreload:
    description: Reload the plugin
    usage: /enhancedhomesreload
    permission: enhancedhomes.enhancedhomesreload